version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/mybatis
      - ~/.m2/repository:/root/.m2/repository
  mysql-test:
    build:
      context: ./mysql
      dockerfile: Dockerfile
